class Player {
    constructor(name, team, picture) {
        this.name = name; // Player's name
        this.team = team; // Player's team
        this.picture = picture; // URL or path to the player's picture
    }
}


const teams = {
    "Boston Celtics": [
        new Player("Jaylen Brown", "Boston Celtics", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3917376.png"),
        new Player("Jayson Tatum", "Boston Celtics", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4065648.png"),
        new Player("Jrue Holiday", "Boston Celtics", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3995.png"),
        new Player("Kristaps Porzingis", "Boston Celtics", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3102531.png"),
        new Player("Derrick White", "Boston Celtics", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3078576.png"),
        new Player("Al Horford", "Boston Celtics", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3213.png"),
        new Player("Payton Pritchard", "Boston Celtics", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630202.png"),
        new Player("Torrey Craig", "Boston Celtics", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2528693.png"),
        new Player("Baylor Scheierman", "Boston Celtics", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631248.png"),
        new Player("Xavier Tillman", "Boston Celtics", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4277964.png"),
        new Player("Neemias Queta", "Boston Celtics", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4397424.png"),
        new Player("Sam Hauser", "Boston Celtics", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630573.png"),
        new Player("Luke Kornet", "Boston Celtics", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3064560.png"),
        new Player("Jordan Walsh", "Boston Celtics", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641775.png"),
    ],
    "Brooklyn Nets": [
        new Player("Nic Claxton", "Brooklyn Nets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629651.png"),
        new Player("Cameron Johnson", "Brooklyn Nets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629661.png"),
        new Player("D'Angelo Russell", "Brooklyn Nets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3136776.png"),
        new Player("De'Anthony Melton", "Brooklyn Nets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066436.png"),
        new Player("Ziaire Williams", "Brooklyn Nets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630533.png"),
        new Player("Cam Thomas", "Brooklyn Nets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432174.png"),
        new Player("Day'Ron Sharpe", "Brooklyn Nets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630549.png"),
        new Player("Noah Clowney", "Brooklyn Nets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641730.png"),
        new Player("Dariq Whitehead", "Brooklyn Nets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641727.png"),
        new Player("Trendon Watford", "Brooklyn Nets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630570.png"),
        new Player("Keon Johnson", "Brooklyn Nets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630553.png"),
        new Player("Jalen Wilson", "Brooklyn Nets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431714.png"),
        new Player("Maxwell Lewis", "Brooklyn Nets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641721.png"),
        new Player("Tyrese Martin", "Brooklyn Nets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631213.png"),
        new Player("Drew Timme", "Brooklyn Nets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631166.png"),
    ],
    "New York Knicks": [
        new Player("Karl-Anthony Towns", "New York Knicks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3136195.png"),
        new Player("OG Anunoby", "New York Knicks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628384.png"),
        new Player("Jalen Brunson", "New York Knicks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3934672.png"),
        new Player("Mikal Bridges", "New York Knicks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3147657.png"),
        new Player("Josh Hart", "New York Knicks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628404.png"),
        new Player("Mitchell Robinson", "New York Knicks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4351852.png"),
        new Player("Precious Achiuwa", "New York Knicks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630173.png"),
        new Player("Miles McBride", "New York Knicks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431823.png"),
        new Player("MarJon Beauchamp", "New York Knicks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630699.png"),
        new Player("Deion Wright", "New York Knicks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1626153.png"),
        new Player("Cameron Payne", "New York Knicks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1626166.png"),
        new Player("Tyler Kolek", "New York Knicks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4433225.png"),
        new Player("Pacome Dadiet", "New York Knicks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642359.png"),
        new Player("Landry Shamet", "New York Knicks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3914044.png"),
        new Player("Ariel Hukporti", "New York Knicks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630574.png"),
        new Player("P.J. Tucker", "New York Knicks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3033.png"),
    ],
    "Philadelphia 76ers": [
        new Player("Joel Embiid", "Philadelphia 76ers", "https://cdn.nba.com/headshots/nba/latest/1040x760/203954.png"),
        new Player("Paul George", "Philadelphia 76ers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4251.png"),
        new Player("Tyrese Maxey", "Philadelphia 76ers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431678.png"),
        new Player("Kelly Oubre Jr.", "Philadelphia 76ers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1626162.png"),
        new Player("Andre Drummond", "Philadelphia 76ers", "https://cdn.nba.com/headshots/nba/latest/1040x760/203083.png"),
        new Player("Quentin Grimes", "Philadelphia 76ers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629656.png"),
        new Player("Jared McCain", "Philadelphia 76ers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642272.png"),
        new Player("Jalen Hood-Schifino", "Philadelphia 76ers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641720.png"),
        new Player("Eric Gordon", "Philadelphia 76ers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3431.png"),
        new Player("Jeff Dowtin Jr.", "Philadelphia 76ers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630288.png"),
        new Player("Guerschon Yabusele", "Philadelphia 76ers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4017844.png"),
        new Player("Kyle Lowry", "Philadelphia 76ers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3012.png"),
        new Player("Ricky Council IV", "Philadelphia 76ers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641741.png"),
        new Player("Adem Bona", "Philadelphia 76ers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5105637.png"),
        new Player("Lonnie Walker IV", "Philadelphia 76ers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4277890.png"),
        new Player("Jared Butler", "Philadelphia 76ers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630215.png"),
        new Player("Justin Edwards", "Philadelphia 76ers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4711297.png"),
    ],
    "Toronto Raptors": [
        new Player("Brandon Ingram", "Toronto Raptors", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3913176.png"),
        new Player("Immanuel Quickley", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630193.png"),
        new Player("RJ Barrett", "Toronto Raptors", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4395625.png"),
        new Player("Jakob Poeltl", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1627751.png"),
        new Player("Chris Boucher", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628449.png"),
        new Player("Scottie Barnes", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630567.png"),
        new Player("Gradey Dick", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641711.png"),
        new Player("Ochai Agbaji", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630534.png"),
        new Player("Ja'Kobe Walter", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642266.png"),
        new Player("Eugene Omoruyi", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630647.png"),
        new Player("A.J. Lawson", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630639.png"),
        new Player("Garrett Temple", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/202066.png"),
        new Player("Jamal Shead", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642347.png"),
        new Player("Jonathan Mogbo", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642367.png"),
        new Player("Jamison Battle", "Toronto Raptors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642419.png"),
    ],
    "Chicago Bulls": [
        new Player("Lonzo Ball", "Chicago Bulls", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628366.png"),
        new Player("Nikola Vucevic", "Chicago Bulls", "https://cdn.nba.com/headshots/nba/latest/1040x760/202696.png"),
        new Player("Patrick Williams", "Chicago Bulls", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630172.png"),
        new Player("Kevin Huerter", "Chicago Bulls", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628989.png"),
        new Player("Zach Collins", "Chicago Bulls", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066650.png"),
        new Player("Coby White", "Chicago Bulls", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629632.png"),
        new Player("Tre Jones", "Chicago Bulls", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630200.png"),
        new Player("Jalen Smith", "Chicago Bulls", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630188.png"),
        new Player("Josh Giddey", "Chicago Bulls", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630581.png"),
        new Player("Ayo Dosunmu", "Chicago Bulls", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4397002.png"),
        new Player("Jevon Carter", "Chicago Bulls", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3133635.png"),
        new Player("Matas Buzelis", "Chicago Bulls", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641824.png"),
        new Player("Dalen Terry", "Chicago Bulls", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4433159.png"),
        new Player("E.J. Liddell", "Chicago Bulls", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630604.png"),
        new Player("Talen Horton-Tucker", "Chicago Bulls", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4396991.png"),
        new Player("Julian Phillips", "Chicago Bulls", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5105553.png"),
    ],
    "Cleveland Cavaliers": [
        new Player("Darius Garland", "Cleveland Cavaliers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629636.png"),
        new Player("Donovan Mitchell", "Cleveland Cavaliers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3908809.png"),
        new Player("De'Andre Hunter", "Cleveland Cavaliers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4065732.png"),
        new Player("Jarrett Allen", "Cleveland Cavaliers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066328.png"),
        new Player("Max Strus", "Cleveland Cavaliers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4065778.png"),
        new Player("Evan Mobley", "Cleveland Cavaliers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630596.png"),
        new Player("Isaac Okoro", "Cleveland Cavaliers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630171.png"),
        new Player("Dean Wade", "Cleveland Cavaliers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629731.png"),
        new Player("Jaylon Tyson", "Cleveland Cavaliers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4683747.png"),
        new Player("Ty Jerome", "Cleveland Cavaliers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4065733.png"),
        new Player("Sam Merrill", "Cleveland Cavaliers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630241.png"),
        new Player("Tristan Thompson", "Cleveland Cavaliers", "https://cdn.nba.com/headshots/nba/latest/1040x760/202684.png"),
        new Player("Craig Porter Jr.", "Cleveland Cavaliers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4701233.png"),
        new Player("Javonte Green", "Cleveland Cavaliers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629750.png"),
    ],
    "Detroit Pistons": [
        new Player("Tobias Harris", "Detroit Pistons", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6440.png"),
        new Player("Tim Hardaway Jr.", "Detroit Pistons", "https://cdn.nba.com/headshots/nba/latest/1040x760/203501.png"),
        new Player("Isaiah Stewart", "Detroit Pistons", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630191.png"),
        new Player("Cade Cunningham", "Detroit Pistons", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432166.png"),
        new Player("Dennis Schroder", "Detroit Pistons", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3032979.png"),
        new Player("Ausar Thompson", "Detroit Pistons", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641709.png"),
        new Player("Ronald Holland II", "Detroit Pistons", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641842.png"),
        new Player("Jaden Ivey", "Detroit Pistons", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631093.png"),
        new Player("Simone Fontecchio", "Detroit Pistons", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3899664.png"),
        new Player("Malik Beasley", "Detroit Pistons", "https://cdn.nba.com/headshots/nba/latest/1040x760/1627736.png"),
        new Player("Jalen Duren", "Detroit Pistons", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4433621.png"),
        new Player("Marcus Sasser", "Detroit Pistons", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432107.png"),
        new Player("Lindy Waters III", "Detroit Pistons", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066317.png"),
        new Player("Paul Reed", "Detroit Pistons", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4278562.png"),
        new Player("Bobi Klintman", "Detroit Pistons", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641752.png"),
    ],
    "Indiana Pacers": [
        new Player("Pascal Siakam", "Indiana Pacers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3149673.png"),
        new Player("Tyrese Haliburton", "Indiana Pacers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630169.png"),
        new Player("Myles Turner", "Indiana Pacers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1626167.png"),
        new Player("Obi Toppin", "Indiana Pacers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630167.png"),
        new Player("Aaron Nesmith", "Indiana Pacers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4396909.png"),
        new Player("T.J. McConnell", "Indiana Pacers", "https://cdn.nba.com/headshots/nba/latest/1040x760/204456.png"),
        new Player("Bennedict Mathurin", "Indiana Pacers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631097.png"),
        new Player("Jarace Walker", "Indiana Pacers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5106060.png"),
        new Player("Isaiah Jackson", "Indiana Pacers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432170.png"),
        new Player("Ben Sheppard", "Indiana Pacers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4433076.png"),
        new Player("James Johnson", "Indiana Pacers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3999.png"),
        new Player("Thomas Bryant", "Indiana Pacers", "https://a.espncdn.com/i/headshots/nba/players/full/3934723.png"),
        new Player("Andrew Nembhard", "Indiana Pacers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4395712.png"),
        new Player("Johnny Furphy", "Indiana Pacers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5157066.png"),
        new Player("Tony Bradley", "Indiana Pacers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628396.png"),
    ],
    "Milwaukee Bucks": [
        new Player("Damian Lillard", "Milwaukee Bucks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6606.png"),
        new Player("Giannis Antetokounmpo", "Milwaukee Bucks", "https://cdn.nba.com/headshots/nba/latest/1040x760/203507.png"),
        new Player("Brook Lopez", "Milwaukee Bucks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3448.png"),
        new Player("Kyle Kuzma", "Milwaukee Bucks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628398.png"),
        new Player("Bobby Portis", "Milwaukee Bucks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3064482.png"),
        new Player("Pat Connaughton", "Milwaukee Bucks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1626192.png"),
        new Player("Kevin Porter Jr.", "Milwaukee Bucks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629645.png"),
        new Player("Stanley Umude", "Milwaukee Bucks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630649.png"),
        new Player("AJ Green", "Milwaukee Bucks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4397475.png"),
        new Player("Jericho Sims", "Milwaukee Bucks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4277922.png"),
        new Player("Gary Trent Jr.", "Milwaukee Bucks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629018.png"),
        new Player("Taurean Prince", "Milwaukee Bucks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2990962.png"),
        new Player("Chris Livingston", "Milwaukee Bucks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641753.png"),
        new Player("Andre Jackson Jr.", "Milwaukee Bucks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641748.png"),
        new Player("Tyler Smith", "Milwaukee Bucks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5167876.png"),
        new Player("Ryan Rollins", "Milwaukee Bucks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631157.png"),
    ],
    "Atlanta Hawks": [
        new Player("Trae Young", "Atlanta Hawks", "https://a.espncdn.com/i/headshots/nba/players/full/4277905.png"),
        new Player("Clint Capela", "Atlanta Hawks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3102529.png"),
        new Player("Caris LeVert", "Atlanta Hawks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1627747.png"),
        new Player("Onyeka Okongwu", "Atlanta Hawks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431680.png"),
        new Player("Zaccharie Risacher", "Atlanta Hawks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5211175.png"),
        new Player("Terance Mann", "Atlanta Hawks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629611.png"),
        new Player("Larry Nance Jr.", "Atlanta Hawks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1626204.png"),
        new Player("Georges Niang", "Atlanta Hawks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1627777.png"),
        new Player("Dyson Daniels", "Atlanta Hawks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4869342.png"),
        new Player("Jalen Johnson", "Atlanta Hawks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630552.png"),
        new Player("Kobe Bufkin", "Atlanta Hawks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641723.png"),
        new Player("Garrison Matthews", "Atlanta Hawks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3913180.png"),
        new Player("Vit Krejci", "Atlanta Hawks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4578893.png"),
        new Player("Mouhamed Gueye", "Atlanta Hawks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4712863.png"),
        new Player("Dominick Barlow", "Atlanta Hawks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631230.png"),
    ],
    "Charlotte Hornets": [
        new Player("LaMelo Ball", "Charlotte Hornets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432816.png"),
        new Player("Miles Bridges", "Charlotte Hornets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628970.png"),
        new Player("Jusuf Nurkic", "Charlotte Hornets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3102530.png"),
        new Player("Grant Williams", "Charlotte Hornets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629684.png"),
        new Player("Josh Green", "Charlotte Hornets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630182.png"),
        new Player("Brandon Miller", "Charlotte Hornets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4433287.png"),
        new Player("Josh Okogie", "Charlotte Hornets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4065663.png"),
        new Player("Tidjane Salaun", "Charlotte Hornets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642275.png"),
        new Player("Tre Mann", "Charlotte Hornets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630544.png"),
        new Player("Mark Williams", "Charlotte Hornets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4701232.png"),
        new Player("Nick Smith Jr.", "Charlotte Hornets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4683686.png"),
        new Player("Wendell Moore Jr.", "Charlotte Hornets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631111.png"),
        new Player("DaQuan Jeffries", "Charlotte Hornets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3913220.png"),
        new Player("Taj Gibson", "Charlotte Hornets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3986.png"),
        new Player("Seth Curry", "Charlotte Hornets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2326307.png"),
        new Player("Moussa Diabate", "Charlotte Hornets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631217.png"),
    ],
    "Miami Heat": [
        new Player("Bam Adebayo", "Miami Heat", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066261.png"),
        new Player("Tyler Herro", "Miami Heat", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629639.png"),
        new Player("Andrew Wiggins", "Miami Heat", "https://cdn.nba.com/headshots/nba/latest/1040x760/203952.png"),
        new Player("Terry Rozier", "Miami Heat", "https://cdn.nba.com/headshots/nba/latest/1040x760/1626179.png"),
        new Player("Duncan Robinson", "Miami Heat", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629130.png"),
        new Player("Kyle Anderson", "Miami Heat", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2993874.png"),
        new Player("Davion Mitchell", "Miami Heat", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4278053.png"),
        new Player("Haywood Highsmith", "Miami Heat", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4291678.png"),
        new Player("Kel'el Ware", "Miami Heat", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5105623.png"),
        new Player("Kevin Love", "Miami Heat", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3449.png"),
        new Player("Jaime Jaquez Jr.", "Miami Heat", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631170.png"),
        new Player("Nikola Jovic", "Miami Heat", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4997528.png"),
        new Player("Alec Burks", "Miami Heat", "https://cdn.nba.com/headshots/nba/latest/1040x760/202692.png"),
        new Player("Pelle Larsson", "Miami Heat", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641796.png"),
        new Player("Keshad Johnson", "Miami Heat", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431786.png"),
    ],
    "Orlando Magic": [
        new Player("Jonathan Isaac", "Orlando Magic", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628371.png"),
        new Player("Kentavious Caldwell-Pope", "Orlando Magic", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2581018.png"),
        new Player("Cole Anthony", "Orlando Magic", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432809.png"),
        new Player("Paolo Banchero", "Orlando Magic", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432573.png"),
        new Player("Wendell Carter Jr.", "Orlando Magic", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628976.png"),
        new Player("Moritz Wagner", "Orlando Magic", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3150844.png"),
        new Player("Jalen Suggs", "Orlando Magic", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432165.png"),
        new Player("Goga Bitadze", "Orlando Magic", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629048.png"),
        new Player("Anthony Black", "Orlando Magic", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4712849.png"),
        new Player("Franz Wagner", "Orlando Magic", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4566434.png"),
        new Player("Gary Harris", "Orlando Magic", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2999547.png"),
        new Player("Jett Howard", "Orlando Magic", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641724.png"),
        new Player("Tristan da Silva", "Orlando Magic", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641783.png"),
        new Player("Cory Joseph", "Orlando Magic", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6446.png"),
        new Player("Caleb Houstan", "Orlando Magic", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4433623.png"),
    ],
    "Washington Wizards": [
        new Player("Khris Middleton", "Washington Wizards", "https://cdn.nba.com/headshots/nba/latest/1040x760/203114.png"),
        new Player("Jordan Poole", "Washington Wizards", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629673.png"),
        new Player("Malcolm Brogdon", "Washington Wizards", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2566769.png"),
        new Player("Marcus Smart", "Washington Wizards", "https://cdn.nba.com/headshots/nba/latest/1040x760/203935.png"),
        new Player("Richaun Holmes", "Washington Wizards", "https://cdn.nba.com/headshots/nba/latest/1040x760/1626158.png"),
        new Player("Alex Sarr", "Washington Wizards", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642259.png"),
        new Player("Bilal Coulibaly", "Washington Wizards", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5104155.png"),
        new Player("Saddiq Bey", "Washington Wizards", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4397136.png"),
        new Player("Corey Kispert", "Washington Wizards", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4280151.png"),
        new Player("Bub Carrington", "Washington Wizards", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4845374.png"),
        new Player("Kyshawn George", "Washington Wizards", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5174563.png"),
        new Player("AJ Johnson", "Washington Wizards", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642358.png"),
        new Player("Tristan Vukcevic", "Washington Wizards", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641774.png"),
        new Player("Anthony Gill", "Washington Wizards", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630264.png"),
        new Player("Colby Jones", "Washington Wizards", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4433378.png"),
        new Player("JT Thor", "Washington Wizards", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630550.png"),
        new Player("Justin Champagnie", "Washington Wizards", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630551.png"),
    ],
    "Golden State Warriors": [
        new Player("Stephen Curry", "Golden State Warriors", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3975.png"),
        new Player("Jimmy Butler III", "Golden State Warriors", "https://cdn.nba.com/headshots/nba/latest/1040x760/202710.png"),
        new Player("Draymond Green", "Golden State Warriors", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6589.png"),
        new Player("Gary Payton II", "Golden State Warriors", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3134903.png"),
        new Player("Buddy Hield", "Golden State Warriors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1627741.png"),
        new Player("Kevon Looney", "Golden State Warriors", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3155535.png"),
        new Player("Jonathan Kuminga", "Golden State Warriors", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4433247.png"),
        new Player("Moses Moody", "Golden State Warriors", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432171.png"),
        new Player("Brandin Podziemski", "Golden State Warriors", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4709138.png"),
        new Player("Gui Santos", "Golden State Warriors", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4997536.png"),
        new Player("Trayce Jackson-Davis", "Golden State Warriors", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431684.png"),
        new Player("Quinten Post", "Golden State Warriors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642366.png"),
        new Player("Pat Spencer", "Golden State Warriors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630311.png"),
        new Player("Kevin Knox II", "Golden State Warriors", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628995.png"),
    ],
    "Los Angeles Clippers": [
        new Player("Kawhi Leonard", "Los Angeles Clippers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6450.png"),
        new Player("James Harden", "Los Angeles Clippers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3992.png"),
        new Player("Norman Powell", "Los Angeles Clippers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1626181.png"),
        new Player("Bogdan Bogdanovic", "Los Angeles Clippers", "https://cdn.nba.com/headshots/nba/latest/1040x760/203992.png"),
        new Player("Ivica Zubac", "Los Angeles Clippers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4017837.png"),
        new Player("Derrick Jones Jr.", "Los Angeles Clippers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1627884.png"),
        new Player("Kris Dunn", "Los Angeles Clippers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2991139.png"),
        new Player("Drew Eubanks", "Los Angeles Clippers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3914285.png"),
        new Player("Nicolas Batum", "Los Angeles Clippers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3416.png"),
        new Player("Amir Coffey", "Los Angeles Clippers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066387.png"),
        new Player("Kobe Brown", "Los Angeles Clippers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431752.png"),
        new Player("Patrick Baldwin Jr.", "Los Angeles Clippers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4433246.png"),
        new Player("Patty Mills", "Los Angeles Clippers", "https://cdn.nba.com/headshots/nba/latest/1040x760/201988.png"),
        new Player("Cam Christie", "Los Angeles Clippers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642353.png"),
        new Player("Jordan Miller", "Los Angeles Clippers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4396818.png"),
        new Player("Ben Simmons", "Los Angeles Clippers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1627732.png"),
    ],
    "Los Angeles Lakers": [
        new Player("LeBron James", "Los Angeles Lakers", "https://cdn.nba.com/headshots/nba/latest/1040x760/2544.png"),
        new Player("Luka Doncic", "Los Angeles Lakers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629029.png"),
        new Player("Rui Hachimura", "Los Angeles Lakers", "https://a.espncdn.com/i/headshots/nba/players/full/4066648.png"),
        new Player("Dorian Finney-Smith", "Los Angeles Lakers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2578185.png"),
        new Player("Austin Reaves", "Los Angeles Lakers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630559.png"),
        new Player("Gabe Vincent", "Los Angeles Lakers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629216.png"),
        new Player("Maxi Kleber", "Los Angeles Lakers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628467.png"),
        new Player("Jarred Vanderbilt", "Los Angeles Lakers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4278077.png"),
        new Player("Dalton Knecht", "Los Angeles Lakers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4897943.png"),
        new Player("Shake Milton", "Los Angeles Lakers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629003.png"),
        new Player("Jaxson Hayes", "Los Angeles Lakers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4397077.png"),
        new Player("Markieff Morris", "Los Angeles Lakers", "https://cdn.nba.com/headshots/nba/latest/1040x760/202693.png"),
        new Player("Bronny James", "Los Angeles Lakers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4683774.png"),
        new Player("Alex Len", "Los Angeles Lakers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2596107.png"),
        new Player("Jordan Goodwin", "Los Angeles Lakers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630692.png"),
    ],
    "Phoenix Suns": [
        new Player("Kevin Durant", "Phoenix Suns", "https://a.espncdn.com/i/headshots/nba/players/full/3202.png"),
        new Player("Bradley Beal", "Phoenix Suns", "https://cdn.nba.com/headshots/nba/latest/1040x760/203078.png"),
        new Player("Devin Booker", "Phoenix Suns", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3136193.png"),
        new Player("Grayson Allen", "Phoenix Suns", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628960.png"),
        new Player("Royce O'Neale", "Phoenix Suns", "https://cdn.nba.com/headshots/nba/latest/1040x760/1626220.png"),
        new Player("Cody Martin", "Phoenix Suns", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628998.png"),
        new Player("Vasilije Micic", "Phoenix Suns", "https://cdn.nba.com/headshots/nba/latest/1040x760/203995.png"),
        new Player("Nick Richards", "Phoenix Suns", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630208.png"),
        new Player("Ryan Dunn", "Phoenix Suns", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4888725.png"),
        new Player("Mason Plumlee", "Phoenix Suns", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2488653.png"),
        new Player("Monte Morris", "Phoenix Suns", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3059310.png"),
        new Player("Damion Lee", "Phoenix Suns", "https://cdn.nba.com/headshots/nba/latest/1040x760/1627814.png"),
        new Player("Tyus Jones", "Phoenix Suns", "https://cdn.nba.com/headshots/nba/latest/1040x760/1626145.png"),
        new Player("Bol Bol", "Phoenix Suns", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629626.png"),
        new Player("Oso Ighodaro", "Phoenix Suns", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642345.png"),
    ],
    "Sacramento Kings": [
        new Player("Zach LaVine", "Sacramento Kings", "https://cdn.nba.com/headshots/nba/latest/1040x760/203897.png"),
        new Player("Domontas Sabonis", "Sacramento Kings", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3155942.png"),
        new Player("DeMar DeRozan", "Sacramento Kings", "https://cdn.nba.com/headshots/nba/latest/1040x760/201942.png"),
        new Player("Malik Monk", "Sacramento Kings", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066262.png"),
        new Player("Jonas Valanciunas", "Sacramento Kings", "https://cdn.nba.com/headshots/nba/latest/1040x760/202685.png"),
        new Player("Keegan Murray", "Sacramento Kings", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631099.png"),
        new Player("Trey Lyles", "Sacramento Kings", "https://cdn.nba.com/headshots/nba/latest/1040x760/1626168.png"),
        new Player("Devin Carter", "Sacramento Kings", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642269.png"),
        new Player("Jake LaRavia", "Sacramento Kings", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631222.png"),
        new Player("Keon Ellis", "Sacramento Kings", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4702177.png"),
        new Player("Doug McDermott", "Sacramento Kings", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2528588.png"),
        new Player("Jae Crowder", "Sacramento Kings", "https://cdn.nba.com/headshots/nba/latest/1040x760/203109.png"),
        new Player("Markelle Fultz", "Sacramento Kings", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066636.png"),
        new Player("Isaac Jones", "Sacramento Kings", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5107818.png"),
    ],
    "Dallas Mavericks": [
        new Player("Anthony Davis", "Dallas Mavericks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6583.png"),
        new Player("Kyrie Irving", "Dallas Mavericks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6442.png"),
        new Player("Klay Thompson", "Dallas Mavericks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6475.png"),
        new Player("P.J. Washington", "Dallas Mavericks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629023.png"),
        new Player("Daniel Gafford", "Dallas Mavericks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629655.png"),
        new Player("Naji Marshall", "Dallas Mavericks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4278594.png"),
        new Player("Caleb Martin", "Dallas Mavericks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628997.png"),
        new Player("Max Christie", "Dallas Mavericks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631108.png"),
        new Player("Dereck Lively II", "Dallas Mavericks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641726.png"),
        new Player("Dwight Powell", "Dallas Mavericks", "https://cdn.nba.com/headshots/nba/latest/1040x760/203939.png"),
        new Player("Dante Exum", "Dallas Mavericks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3102528.png"),
        new Player("Olivier-Maxence Prosper", "Dallas Mavericks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4595400.png"),
        new Player("Kai Jones", "Dallas Mavericks", "https://a.espncdn.com/i/headshots/nba/players/full/4431699.png"),
        new Player("Spencer Dinwiddie", "Dallas Mavericks", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2580782.png"),
        new Player("Jaden Hardy", "Dallas Mavericks", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630702.png"),
    ],
    "Houston Rockets": [
        new Player("Fred VanVleet", "Houston Rockets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2991230.png"),
        new Player("Dillon Brooks", "Houston Rockets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3155526.png"),
        new Player("Steven Adams", "Houston Rockets", "https://cdn.nba.com/headshots/nba/latest/1040x760/203500.png"),
        new Player("Jalen Green", "Houston Rockets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630224.png"),
        new Player("Reed Sheppard", "Houston Rockets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4711272.png"),
        new Player("Jabari Smith Jr.", "Houston Rockets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432639.png"),
        new Player("Amen Thompson", "Houston Rockets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4684740.png"),
        new Player("Jock Landale", "Houston Rockets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3146557.png"),
        new Player("Jeff Green", "Houston Rockets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3209.png"),
        new Player("Jae'Sean Tate", "Houston Rockets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630256.png"),
        new Player("Alperen Sengun", "Houston Rockets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630578.png"),
        new Player("Aaron Holiday", "Houston Rockets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628988.png"),
        new Player("Tari Eason", "Houston Rockets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631106.png"),
        new Player("Cam Whitmore", "Houston Rockets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5105592.png"),
        new Player("David Roddy", "Houston Rockets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4593041.png"),
        new Player("Nate Williams", "Houston Rockets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631466.png"),
    ],
    "Memphis Grizzlies": [
        new Player("Ja Morant", "Memphis Grizzlies", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629630.png"),
        new Player("Desmond Bane", "Memphis Grizzlies", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066320.png"),
        new Player("Jaren Jackson Jr.", "Memphis Grizzlies", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4277961.png"),
        new Player("Brandon Clarke", "Memphis Grizzlies", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629634.png"),
        new Player("Marvin Bagley III", "Memphis Grizzlies", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4277848.png"),
        new Player("Luke Kennard", "Memphis Grizzlies", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3913174.png"),
        new Player("John Konchar", "Memphis Grizzlies", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629723.png"),
        new Player("Zach Edey", "Memphis Grizzlies", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4600663.png"),
        new Player("Santi Aldama", "Memphis Grizzlies", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4593125.png"),
        new Player("Vince Williams Jr.", "Memphis Grizzlies", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4397227.png"),
        new Player("Jay Huff", "Memphis Grizzlies", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630643.png"),
        new Player("Scotty Pippen Jr.", "Memphis Grizzlies", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431785.png"),
        new Player("GG Jackson", "Memphis Grizzlies", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641713.png"),
        new Player("Jaylen Wells", "Memphis Grizzlies", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5112087.png"),
        new Player("Lamar Stevens", "Memphis Grizzlies", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630205.png"),
    ],
    "New Orleans Pelicans": [
        new Player("Zion Williamson", "New Orleans Pelicans", "https://a.espncdn.com/i/headshots/nba/players/full/4395628.png"),
        new Player("CJ McCollum", "New Orleans Pelicans", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2490149.png"),
        new Player("Dejounte Murray", "New Orleans Pelicans", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3907497.png"),
        new Player("Bruce Brown", "New Orleans Pelicans", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4065670.png"),
        new Player("Herbert Jones", "New Orleans Pelicans", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4277813.png"),
        new Player("Kelly Olynyk", "New Orleans Pelicans", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2489663.png"),
        new Player("Trey Murphy III", "New Orleans Pelicans", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4397688.png"),
        new Player("Jordan Hawkins", "New Orleans Pelicans", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641722.png"),
        new Player("Yves Missi", "New Orleans Pelicans", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5061589.png"),
        new Player("Jeremiah Robinson-Earl", "New Orleans Pelicans", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432813.png"),
        new Player("Jose Alvarado", "New Orleans Pelicans", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630631.png"),
        new Player("Karlo Matkovic", "New Orleans Pelicans", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631255.png"),
        new Player("Antonio Reeves", "New Orleans Pelicans", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4592686.png"),
        new Player("Brandon Boston", "New Orleans Pelicans", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630527.png"),
    ],
    "San Antonio Spurs": [
        new Player("De'Aaron Fox", "San Antonio Spurs", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628368.png"),
        new Player("Devin Vassell", "San Antonio Spurs", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4395630.png"),
        new Player("Keldon Johnson", "San Antonio Spurs", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4395723.png"),
        new Player("Harrison Barnes", "San Antonio Spurs", "https://cdn.nba.com/headshots/nba/latest/1040x760/203084.png"),
        new Player("Victor Wembanyama", "San Antonio Spurs", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5104157.png"),
        new Player("Chris Paul", "San Antonio Spurs", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2779.png"),
        new Player("Stephon Castle", "San Antonio Spurs", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642264.png"),
        new Player("Jeremy Sochan", "San Antonio Spurs", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631110.png"),
        new Player("Malaki Branham", "San Antonio Spurs", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631103.png"),
        new Player("Julian Champagnie", "San Antonio Spurs", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630577.png"),
        new Player("Blake Wesley", "San Antonio Spurs", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631104.png"),
        new Player("Jordan McLaughlin", "San Antonio Spurs", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629162.png"),
        new Player("Sandro Mamukelashvili", "San Antonio Spurs", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630572.png"),
        new Player("Charles Bassey", "San Antonio Spurs", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629646.png"),
        new Player("Bismack Biyombo", "San Antonio Spurs", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/6427.png"),
    ],
    "Denver Nuggets": [
        new Player("Nikola Jokic", "Denver Nuggets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3112335.png"),
        new Player("Jamal Murray", "Denver Nuggets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3936299.png"),
        new Player("Michael Porter Jr.", "Denver Nuggets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629008.png"),
        new Player("Aaron Gordon", "Denver Nuggets", "https://cdn.nba.com/headshots/nba/latest/1040x760/203932.png"),
        new Player("Zeke Nnaji", "Denver Nuggets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431690.png"),
        new Player("Dario Saric", "Denver Nuggets", "https://cdn.nba.com/headshots/nba/latest/1040x760/203967.png"),
        new Player("Russell Westbrook", "Denver Nuggets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3468.png"),
        new Player("Christian Braun", "Denver Nuggets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431767.png"),
        new Player("DaRon Holmes II", "Denver Nuggets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4433607.png"),
        new Player("Julian Strawther", "Denver Nuggets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432181.png"),
        new Player("Peyton Watson", "Denver Nuggets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631212.png"),
        new Player("DeAndre Jordan", "Denver Nuggets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3442.png"),
        new Player("Vlatko Cancar", "Denver Nuggets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628427.png"),
        new Player("Hunter Tyson", "Denver Nuggets", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641816.png"),
        new Player("Jalen Pickett", "Denver Nuggets", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4398390.png"),
    ],
    "Minnesota Timberwolves": [
        new Player("Rudy Gobert", "Minnesota Timberwolves", "https://cdn.nba.com/headshots/nba/latest/1040x760/203497.png"),
        new Player("Anthony Edwards", "Minnesota Timberwolves", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4594268.png"),
        new Player("Julius Randle", "Minnesota Timberwolves", "https://cdn.nba.com/headshots/nba/latest/1040x760/203944.png"),
        new Player("Jaden McDaniels", "Minnesota Timberwolves", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630183.png"),
        new Player("Naz Reid", "Minnesota Timberwolves", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629675.png"),
        new Player("Donte DiVincenzo", "Minnesota Timberwolves", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3934673.png"),
        new Player("Mike Conley", "Minnesota Timberwolves", "https://cdn.nba.com/headshots/nba/latest/1040x760/201144.png"),
        new Player("Rob Dillingham", "Minnesota Timberwolves", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4684275.png"),
        new Player("Nickeil Alexander-Walker", "Minnesota Timberwolves", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629638.png"),
        new Player("Bones Hyland", "Minnesota Timberwolves", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4592492.png"),
        new Player("Terrence Shannon Jr.", "Minnesota Timberwolves", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630545.png"),
        new Player("Luka Garza", "Minnesota Timberwolves", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4277951.png"),
        new Player("Joe Ingles", "Minnesota Timberwolves", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2968436.png"),
        new Player("Josh Minott", "Minnesota Timberwolves", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631169.png"),
        new Player("Leonard Miller", "Minnesota Timberwolves", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631159.png"),
        new Player("Jaylen Clark", "Minnesota Timberwolves", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641740.png"),
    ],
    "Oklahoma City Thunder": [
        new Player("Shai Gilgeous-Alexander", "Oklahoma City Thunder", "https://cdn.nba.com/headshots/nba/latest/1040x760/1628983.png"),
        new Player("Isaiah Hartenstein", "Oklahoma City Thunder", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4222252.png"),
        new Player("Luguentz Dort", "Oklahoma City Thunder", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4397020.png"),
        new Player("Isaiah Joe", "Oklahoma City Thunder", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4395702.png"),
        new Player("Chet Holmgren", "Oklahoma City Thunder", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631096.png"),
        new Player("Aaron Wiggins", "Oklahoma City Thunder", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4397183.png"),
        new Player("Alex Caruso", "Oklahoma City Thunder", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2991350.png"),
        new Player("Kenrich Williams", "Oklahoma City Thunder", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3133626.png"),
        new Player("Cason Wallace", "Oklahoma City Thunder", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641717.png"),
        new Player("Ousmane Dieng", "Oklahoma City Thunder", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631172.png"),
        new Player("Nikola Topic", "Oklahoma City Thunder", "https://cdn.nba.com/headshots/nba/latest/1040x760/1642260.png"),
        new Player("Jalen Willaims", "Oklahoma City Thunder", "https://www.pngplay.com/wp-content/uploads/14/Teletubbies-Full-PNG-HD-Quality.png"),
        new Player("Ajay Mitchell", "Oklahoma City Thunder", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4900671.png"),
        new Player("Dillon Jones", "Oklahoma City Thunder", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4702159.png"),
        new Player("Jaylin Williams", "Oklahoma City Thunder", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432823.png"),
        new Player("Branden Carlson", "Oklahoma City Thunder", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4592435.png"),
    ],
    "Portland Trail Blazers": [
        new Player("Deandre Ayton", "Portland Trail Blazers", "https://a.espncdn.com/i/headshots/nba/players/full/4278129.png"),
        new Player("Jerami Grant", "Portland Trail Blazers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/2991070.png"),
        new Player("Anfernee Simons", "Portland Trail Blazers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629014.png"),
        new Player("Deni Avdija", "Portland Trail Blazers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1630166.png"),
        new Player("Robert Williams III", "Portland Trail Blazers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629057.png"),
        new Player("Matisse Thybulle", "Portland Trail Blazers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3907498.png"),
        new Player("Scoot Henderson", "Portland Trail Blazers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4683678.png"),
        new Player("Shaedon Sharpe", "Portland Trail Blazers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1631101.png"),
        new Player("Donovan Clingan", "Portland Trail Blazers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5105565.png"),
        new Player("Kris Murray", "Portland Trail Blazers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4594326.png"),
        new Player("Dalano Banton", "Portland Trail Blazers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4397885.png"),
        new Player("Duop Reath", "Portland Trail Blazers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066268.png"),
        new Player("Jabari Walker", "Portland Trail Blazers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432446.png"),
        new Player("Bryce McGowens", "Portland Trail Blazers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4576086.png"),
        new Player("Rayan Rupert", "Portland Trail Blazers", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641712.png"),
        new Player("Sidy Cissoko", "Portland Trail Blazers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5081727.png"),
        new Player("Toumani Camara", "Portland Trail Blazers", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4431736.png"),
    ],
    "Utah Jazz": [
        new Player("Lauri Markkanen", "Utah Jazz", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4066336.png"),
        new Player("John Collins", "Utah Jazz", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3908845.png"),
        new Player("Collin Sexton", "Utah Jazz", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629012.png"),
        new Player("Jordan Clarkson", "Utah Jazz", "https://cdn.nba.com/headshots/nba/latest/1040x760/203903.png"),
        new Player("KJ Martin", "Utah Jazz", "https://a.espncdn.com/i/headshots/nba/players/full/4431828.png"),
        new Player("Taylor Hendricks", "Utah Jazz", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4684806.png"),
        new Player("Cody Williams", "Utah Jazz", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4895758.png"),
        new Player("Keyonte George", "Utah Jazz", "https://cdn.nba.com/headshots/nba/latest/1040x760/1641718.png"),
        new Player("Svi Mykhailiuk", "Utah Jazz", "https://cdn.nba.com/headshots/nba/latest/1040x760/1629004.png"),
        new Player("Johnny Juzang", "Utah Jazz", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432817.png"),
        new Player("Kyle Filipowski", "Utah Jazz", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4684793.png"),
        new Player("Walker Kessler", "Utah Jazz", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4433136.png"),
        new Player("Brice Sensabaugh", "Utah Jazz", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/5105839.png"),
        new Player("Isaiah Collier", "Utah Jazz", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4683766.png"),
        new Player("Jaden Springer", "Utah Jazz", "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/4432164.png"),
    ],
};

export { teams };